config:
  run: AMP-CL-DDP
  data-dir: /home/usyd-04a/synthetic/
  checkpoint-dir: /home/usyd-04a/checkpoints/fcn
  classes: 2
  amp: True
  channels-last: True
  distributed: True

hyper-params:
  batch-size: 64
  learning-rate: 0.0001
  epochs: 10
  workers: 2

distributed:
  nodes: 1
  ip-address: localhost
  ngpus: null
  local-ranks: 0

wandb:
  enabled: True
  project-name: FCN-Benchmark