config:
  run: Cuda-graphs
  data-dir: /home/usyd-04a/benchmark_dataset/synthetic/
  checkpoint-dir: /home/usyd-04a/checkpoints/fcn
  classes: 2

hyper-params:
  batch-size: 32
  learning-rate: 0.0001
  epochs: 1
  workers: 6

amp:
  enabled: True

channels-last:
  enabled: False

distributed:
  enabled: True
  nodes: 1
  ip-address: localhost
  ngpus: null
  local-ranks: 0

cuda-graphs:
  enabled: True
  warmup-iters: 1

meProp:
  enabled: False

wandb:
  enabled: False
  project-name: FCN-Benchmark