config:
  run: Unet-demo
  data-dir: /home/usyd-04a/synthetic/
  checkpoint-dir: /home/usyd-04a/checkpoints/unet
  classes: 2

hyper-params:
  batch-size: 48
  learning-rate: 0.0001
  epochs: 10
  workers: 4

amp:
  enabled: False

channels-last:
  enabled: False

distributed:
  enabled: True
  nodes: 1
  ip-address: localhost
  ngpus: null
  local-ranks: 0

cuda-graphs:
  enabled: False
  warmup-iters: 15

wandb:
  enabled: True
  project-name: Unet-Demo