config:
  run: AMP-CL
  data-dir: /home/usyd-04a/benchmark_dataset/synthetic/
  checkpoint-dir: /home/usyd-04a/checkpoints/unet
  classes: 2
  amp: True
  channels-last: True
  distributed: False

hyper-params:
  batch-size: 64
  learning-rate: 0.0001
  epochs: 10
  workers: 4

distributed:
  nodes: 1
  ip-address: localhost
  ngpus: null
  local-ranks: 0

wandb:
  enabled: True
  project-name: UNET-Benchmark