config:
  run: AMP-DDP
  data-dir: /home/usyd-04a/synthetic/
  checkpoint-dir: /home/usyd-04a/checkpoints/mask
  classes: 2

hyper-params:
  batch-size: 64
  learning-rate: 0.0001
  epochs: 3
  workers: 4

amp:
  enabled: True

channels-last:
  enabled: False

distributed:
  enabled: True
  nodes: 1
  ip-address: localhost
  ngpus: null
  local-ranks: 0

cuda-graphs:
  enabled: False
  warmup-iters: 1

wandb:
  enabled: True
  project-name: Mask-RCNN